INSERT INTO ingredients (category, title)
VALUES
    ('fruit', 'apples'),
    ('fruit', 'avocado'),
    ('fruit', 'bananas'),
    ('fruit', 'blueberries'),
    ('fruit', 'cherries'),
    ('fruit', 'cucumber'),
    ('fruit', 'grapes'),
    ('fruit', 'grapefruit'),
    ('fruit', 'lemon'),
    ('fruit', 'lime'),
    ('fruit', 'mango'),
    ('fruit', 'papaya'),
    ('fruit', 'peaches'),
    ('fruit', 'pineapple'),
    ('fruit', 'raspberries'),
    ('fruit', 'strawberries'),
    ('vegetables', 'beets'),
    ('vegetables', 'broccoli'),
    ('vegetables', 'carrots'),
    ('vegetables', 'carrot tops'),
    ('vegetables', 'chard'),
    ('vegetables', 'celery'),
    ('vegetables', 'kale'),
    ('vegetables', 'romaine lettuce'),
    ('vegetables', 'spinach'),
    ('nuts & seeds', 'almonds'),
    ('nuts & seeds', 'almond butter'),
    ('nuts & seeds', 'cashews'),
    ('nuts & seeds', 'cashew butter'),
    ('nuts & seeds', 'chia seeds'),
    ('nuts & seeds', 'flax seeds'),
    ('nuts & seeds', 'peanuts'),
    ('nuts & seeds', 'peanut butter'),
    ('nuts & seeds', 'walnuts'),
    ('liquids', 'almond milk'),
    ('liquids', 'cashew milk'),
    ('liquids', 'coconut milk'),
    ('liquids', 'coconut water'),
    ('liquids', 'hemp milk'),
    ('liquids', 'milk'),
    ('liquids', 'oat milk'),
    ('liquids', 'orange juice'),
    ('liquids', 'pineapple juice'),
    ('liquids', 'soy milk'),
    ('liquids', 'water'),
    ('powders', 'cacao'),
    ('powders', 'cinnamon'),
    ('powders', 'greens powder'),
    ('powders', 'maca'),
    ('powders', 'pea protein'),
    ('powders', 'rice protein'),
    ('powders', 'soy protein'),
    ('powders', 'turmeric'),
    ('powders', 'whey protein'),
    ('sweeteners', 'blue agave'),
    ('sweeteners', 'coconut syrup'),
    ('sweeteners', 'honey'),
    ('sweeteners', 'maple syrup'),
    ('sweeteners', 'monk fruit'),
    ('sweeteners', 'stevia'),
    ('sweeteners', 'xylitol'),
    ('other', 'cacao nibs'),
    ('other', 'chocolate, dark'),
    ('other', 'chocolate, milk'),
    ('other', 'coconut oil'),
    ('other', 'flaxseed oil'),
    ('other', 'ginger'),
    ('other', 'granola'),
    ('other', 'ice cubes'),
    ('other', 'lemon juice'),
    ('other', 'lime juice'),
    ('other', 'mint leaves'),
    ('other', 'rolled oats'),
    ('other', 'vanilla extract'),
    ('other', 'yogurt');